spring:  
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      # routes:
      #    - id: eureka-client
      #      uri: lb://eureka-client
      #      predicates:
      #         - Path=/controller/**