spring:  
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
         - id: task
           uri: lb://task
           predicates:
              - Path=/todo/**
    
