spring:  
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
         - id: planner-todo-service
           uri: lb://planner-todo-service
           predicates:
              - Path=/todo/**
    